// Generated by CoffeeScript 1.4.0
(function() {
  var Reddit, nodeio, output, scores, titles,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  nodeio = require('node.io');

  titles = [];

  scores = [];

  output = [];

  Reddit = (function(_super) {

    __extends(Reddit, _super);

    function Reddit() {
      return Reddit.__super__.constructor.apply(this, arguments);
    }

    Reddit.prototype.input = false;

    Reddit.prototype.run = function() {
      var _this = this;
      return this.getHtml('http://bj.fangjia.com/ershoufang/--r-%E6%98%8C%E5%B9%B3', function(err, $, data) {
        if (err) {
          _this.exit(err);
        }
        $('div.items').each(function(a) {
          return console.log(a.rawtext);
        });
        /*
                    @exit 'Title / score mismatch' if scores.length isnt titles.length
        
                    for score, i in scores
                    if score is '&bull;' then continue
                    @assert(score).isInt()
                    output.push '[' + score + '] ' + titles[i]
        */

        return _this.emit(output);
      });
    };

    return Reddit;

  })(nodeio.JobClass);

  this["class"] = Reddit;

  this.job = new Reddit({
    timeout: 10
  });

}).call(this);
